/**************************************************************************
 Copyright (C) 2019 Briac Pilpré

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/
package net.briac.sdlppx;

import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.ResourceBundle;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactoryConfigurationError;

import org.xml.sax.SAXException;

/**
 *
 * @author briac
 */
public class SDLPPXPackagerWindow extends javax.swing.JFrame {
    private static final long serialVersionUID = 4680402377569998598L;
    private final ResourceBundle bundle;
    private static final String SDLPPX_EXT = ".sdlppx";

    /**
     * Creates new form SDLPPXPackagerWindow
     */
    public SDLPPXPackagerWindow() {
        
        bundle = ResourceBundle.getBundle("net.briac.sdlppx.Strings");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("serial")
    private void initComponents() {

        sdlppxFile = new javax.swing.JTextField();
        sdlppxFile.setDropTarget(new DropTarget() {
            @SuppressWarnings("unchecked")
            public synchronized void drop(DropTargetDropEvent evt) {
                try {
                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>) evt
                    .getTransferable().getTransferData(
                        DataFlavor.javaFileListFlavor);
                    for (File file : droppedFiles) {
                        sdlppxFile.setText(file.getAbsolutePath());
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        sdlppxButton = new javax.swing.JButton();
        sdlppxLabel = new javax.swing.JLabel();
        targetLabel = new javax.swing.JLabel();
        targetDir = new javax.swing.JTextField();
        targetDir.setDropTarget(new DropTarget() {
            @SuppressWarnings("unchecked")
            public synchronized void drop(DropTargetDropEvent evt) {
                try {
                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>) evt
                    .getTransferable().getTransferData(
                        DataFlavor.javaFileListFlavor);
                    for (File file : droppedFiles) {
                        targetDir.setText(file.getAbsolutePath());
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        targetButton = new javax.swing.JButton();
        createPackageButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        extractSourceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("SDLPPX_TITLE")); // NOI18N

        sdlppxButton.setText(bundle.getString("SDLPPX_FILE_SELECT")); // NOI18N
        sdlppxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdlppxButtonActionPerformed(evt);
            }
        });

        sdlppxLabel.setText(bundle.getString("SDLPPX_FILE")); // NOI18N

        targetLabel.setText(bundle.getString("PROJECT_DIRECTORY")); // NOI18N

        targetButton.setText(bundle.getString("PROJECT_DIR_SELECT")); // NOI18N
        targetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetButtonActionPerformed(evt);
            }
        });

        createPackageButton.setText(bundle.getString("CONVERT_BUTTON")); // NOI18N
        createPackageButton.setActionCommand(bundle.getString("CONVERT_BUTTON")); // NOI18N
        createPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPackageButtonActionPerformed(evt);
            }
        });

        extractSourceButton.setText(bundle.getString("EXTRACT_BUTTON")); // NOI18N
        extractSourceButton.setActionCommand(bundle.getString("CONVERT_BUTTON")); // NOI18N
        extractSourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractSourceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sdlppxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(targetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(targetDir, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                            .addComponent(sdlppxFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sdlppxButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(targetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(extractSourceButton)))
                        .addGap(18, 18, 18)
                        .addComponent(createPackageButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdlppxFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdlppxButton)
                    .addComponent(sdlppxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetLabel)
                    .addComponent(targetDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createPackageButton)
                        .addComponent(extractSourceButton))
                    .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sdlppxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdlppxButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return false;
                }
                return f.getName().toLowerCase().endsWith(SDLPPX_EXT);
            }

            @Override
            public String getDescription() {
                return bundle.getString("SDLPPX_FILE_DESC");
            }
            
        });
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
               sdlppxFile.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_sdlppxButtonActionPerformed

    private void targetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
               targetDir.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_targetButtonActionPerformed

    private void createPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPackageButtonActionPerformed
        boolean isOk = false;
        String errMsg = null;
        try {
            SDLPPXPackager sp = new SDLPPXPackager(sdlppxFile.getText(), targetDir.getText());
            isOk = sp.updateSdlppx();
        } catch (IOException | ParserConfigurationException | SAXException | TransformerFactoryConfigurationError
                | TransformerException e) {
            errMsg = e.getLocalizedMessage();
        }
        if (isOk) {
            JOptionPane.showMessageDialog(this, bundle.getString("PACKAGE_CREATED"), bundle.getString("SDLPPX_TITLE"),
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, String.format(bundle.getString("PACKAGE_ERROR"), errMsg), bundle.getString("SDLPPX_TITLE"),
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createPackageButtonActionPerformed

    private void extractSourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractSourceButtonActionPerformed
        boolean isOk = false;
        String errMsg = null;
        try {
            SDLPPXPackager sp = new SDLPPXPackager(sdlppxFile.getText(), targetDir.getText());
            isOk = sp.extractSource();
        } catch (Exception e) {
            errMsg = e.getLocalizedMessage();
        }
        if (isOk) {
            JOptionPane.showMessageDialog(this, bundle.getString("SOURCE_EXTRACTED"), bundle.getString("SDLPPX_TITLE"),
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, String.format(bundle.getString("SOURCE_ERROR"), errMsg), bundle.getString("SDLPPX_TITLE"),
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_extractSourceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SDLPPXPackagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SDLPPXPackagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SDLPPXPackagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SDLPPXPackagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDLPPXPackagerWindow().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPackageButton;
    private javax.swing.JButton extractSourceButton;
    private javax.swing.JButton sdlppxButton;
    private javax.swing.JTextField sdlppxFile;
    private javax.swing.JLabel sdlppxLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton targetButton;
    private javax.swing.JTextField targetDir;
    private javax.swing.JLabel targetLabel;
    // End of variables declaration//GEN-END:variables
}
